apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z38ye1nhz-nodejs
  janus-idp.io/tekton: z38ye1nhz-nodejs
  backstage.io/kubernetes-id: z38ye1nhz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z38ye1nhz-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
